### GET request with a header
GET http://127.0.0.1:8000

### POST new event
POST http://127.0.0.1:8000/events/
Content-Type: application/json
{
  "title": "curl event",
  "description": "test event from terminal",
  "author": "curl",
  "date": "hello world",
  "location": "here",
  "status": null
}
