# Generated by Django 4.1.6 on 2023-02-08 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PRIVATE', 'Private'), ('PUBLIC', 'Public'), ('REMOVED', 'Removed'), ('UNDEFINED', 'Undefined')], default='DRAFT', max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribed_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
