# Generated by Django 4.1.6 on 2023-02-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PRIVATE', 'Private'), ('PUBLIC', 'Public'), ('REMOVED', 'Removed'), ('UNDEFINED', 'Undefined')], default='DRAFT', max_length=16),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
