# Generated by Django 4.1.6 on 2023-02-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('private', 'Private'), ('public', 'Public'), ('deleted', 'Deleted')], default='draft', max_length=200),
        ),
    ]
